Update for libdaos.so.1 major API version bump
daos-stack/mpi4py pull request #6
Opened 2020-12-15 03:43 UTC by kccain

PR-repos: daos@PR-3935:14
PR-repos: mpich@PR-44:2

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

2020-12-15 04:39 UTC, brianjmurrell commented
Update the `packaging/` directory before going further.

2020-12-18 18:52 UTC, brianjmurrell requested changes

2020-12-18 18:52 UTC, brianjmurrell commented on mpi4py.spec
> + module_load mpich;
You dropped a line continuator here:
```suggestion
 module_load mpich; \
```

2021-01-07 18:35 UTC, brianjmurrell requested changes
This looks like another that doesn't need a rebuild.

2021-01-07 18:35 UTC, brianjmurrell commented on packaging/Dockerfile.centos.7
> +# Copyright 2018-2020, Intel Corporation
```suggestion
# Copyright 2018-2021, Intel Corporation
```

2021-01-07 18:35 UTC, brianjmurrell commented on packaging/Dockerfile.mockbuild
> +# Copyright 2018-2020, Intel Corporation
```suggestion
# Copyright 2018-2021, Intel Corporation
```

2021-01-07 18:35 UTC, brianjmurrell commented on packaging/Dockerfile.ubuntu.20.04
> +# Copyright 2019-2020, Intel Corporation
```suggestion
# Copyright 2019-2021, Intel Corporation
```

2021-01-23 01:10 UTC, kccain commented
This PR is not needed, closing.

2021-01-23 01:10 UTC, closed without merging